version: "3.5"

volumes:
  data:

services:
  database:
    image: postgres:latest
    container_name: postgres-test
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=DB_SECURITY
    volumes:
      - data:/var/lib/postgresql/data