// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Security.Infrastructure.Models;

public partial class Address
{
    public Guid Id { get; set; }

    public string Street { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string PostalCode { get; set; }

    public string Country { get; set; }

    public Guid UserId { get; set; }

    public virtual User User { get; set; }
}