// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Security.Infrastructure.Models;

public partial class Contact
{
    public Guid Id { get; set; }

    public int? TypeId { get; set; }

    public string Description { get; set; }

    public Guid UserId { get; set; }

    public virtual ContactType Type { get; set; }

    public virtual User User { get; set; }
}